package com.sample.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeAllPropertiesEquals(Mode expected, Mode actual) {
        assertModeAutoGeneratedPropertiesEquals(expected, actual);
        assertModeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeAllUpdatablePropertiesEquals(Mode expected, Mode actual) {
        assertModeUpdatableFieldsEquals(expected, actual);
        assertModeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeAutoGeneratedPropertiesEquals(Mode expected, Mode actual) {
        assertThat(actual)
            .as("Verify Mode auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeUpdatableFieldsEquals(Mode expected, Mode actual) {
        assertThat(actual)
            .as("Verify Mode relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHandle()).as("check handle").isEqualTo(expected.getHandle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeUpdatableRelationshipsEquals(Mode expected, Mode actual) {
        // empty method
    }
}
